import Head from 'next/head'
import WalletModal from '@/components/WalletModal'
import styles from '@/styles/landing.module.css'
// import ThreeCanvas from '@/components/fiber/ThreeCanvas'

const Home = (): any => {
  // console.log({ JSONRPC_URLSssss: JSONRPC_URLS })
  return (
    <>
      <Head>
        <title>THE DAPP | its cool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ThreeCanvas /> */}
      <div className={styles.container}>
        <main>
          {[...Array(50)].map((content, i) => (
            <p key={i}>main content</p>
          ))}
        </main>
      </div>
      <WalletModal />
    </>
  )
}

export default Home
