# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main, staging, dev]
  pull_request:
    branches: [main, staging, dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: npm install
        run: npm install
      # - name: install amplify cli
      #   run: sudo npm install -g @aws-amplify/cli
      # - name: pull amplify
      #   run: npm run amplify:pull
      #   env:
      #     AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
      #     HEADLESS_ACCESS_KEYID: ${{ secrets.HEADLESS_ACCESS_KEYID }}
      #     HEADLESS_SECRET_KEYID: ${{ secrets.HEADLESS_SECRET_KEYID }}
      #     AMPLIFY_ENV: dev
      - name: npm run prettier
        run: npm run prettier
      - name: run linters
        run: npm run lint
      - name: run tests
        run: npm run hardhat:test
        env:
          INFURA_PRIVATE_KEY: ${{ secrets.INFURA_PRIVATE_KEY }}
        # run: npm run jest
        # run: npm run cypress:run
      - name: build the nextjs project
        run: npm run build
      # - name: export for amplify
      #   run: npm run amplify:export
